### ISSUE TITLE
Should data have sample data in it instead of real data?

### ISSUE THREAD

**Issue by simonv3** [bnvk/Beardo#4]
Is it sample data at the moment? If someone forks from this repo to use this, will they overwrite your data and push it?

I'm not sure what your plan is here - it's a cool way to back up your own data, but could start getting tricky further down the line if people want to use it as well? (me).

**Comment by bnvk** [comment]
@simonv3 you're absolutely right about this. I've been throwing things together ad-hoc as I need for my real use cases. I just pushed an update that did the following:

- Removed my personal data
- Added template .json and .csv files
- Added the `--input` arg that loads a given file

It'd be great if you pulled and tested playing with some data :)

My larger goal is implement it as a per [Data Packages](http://data.okfn.org/doc/data-package) so that it's easy to pull around, replicate and munge differing type of data files!

**Comment by simonv3** [comment]
I'll try using it with a new project. I had a look at Data Packages, and it looks like you're pretty much already there.
